name: allure-python-pytest

on:
  push:
    branches-ignore:
      - '!master'
jobs:
  autotests:
    name: Run tests and generate Allure Report

    runs-on:
     - tests
    container:
      image: ubuntu:22.04
      env:
        URL: https://registration-ui.kube.cfi-dev.tech
        URL_LOGIN: https://client-portal-api.kube.cfi-dev.tech
        URL_LOGIN2: https://client-portal-ui.kube.cfi-dev.tech
        URL_API: https://registration-api.kube.cfi-dev.tech
    steps:
      - uses: actions/checkout@v3

      - name: Install base packages
        run: |
          apt update
          apt install -y sudo wget curl unzip libssl-dev python3-pip xvfb
      - name: Check external IP
        run: |
          curl -s ip.flant.com || true
      - name: Install chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
          apt update
          apt install -y google-chrome-stable
      - uses: nanasess/setup-chromedriver@v2

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & # optional
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Test
        if: always()
        run: pytest --remote True app/tests/test_url_connection.py
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history